version: '3'


services:
  db: 
    image: mongo:latest
    ports:
       - 8081:8081
       - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=renew
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
<<<<<<< HEAD
      - ./backend:/opt/renew-back
    depends_on:
      - db 
=======
      - ./backend:/opt/renew-backend 
      - back_modules:/opt/renew-backend/node_modules
>>>>>>> master
  frontend:
    build: ./frontend
    ports:
      - 8080:3000
    volumes:
      - ./frontend:/opt/renew-frontend
      - front_modules:/opt/renew-frontend/node_modules
  
volumes:
    front_modules:
    back_modules:
    